In [1]:
import numpy as np
import torch

In [2]:
tensor = torch.rand(4,3)
tensor

tensor([[0.4110, 0.9321, 0.9295],
        [0.7762, 0.2285, 0.1849],
        [0.2108, 0.8715, 0.2934],
        [0.4271, 0.5311, 0.7229]])

In [3]:
type(tensor)

torch.Tensor

In [5]:
numpy_from_tensor = tensor.numpy()
numpy_from_tensor

array([[0.41099256, 0.93208367, 0.92951626],
       [0.7761659 , 0.22850627, 0.18490869],
       [0.21079338, 0.87147474, 0.29337204],
       [0.42711508, 0.5311391 , 0.72290164]], dtype=float32)

In [6]:
type(numpy_from_tensor)

numpy.ndarray

In [7]:
torch.is_tensor(tensor)

True

In [8]:
torch.is_tensor(numpy_from_tensor)

False

In [9]:
# numpy array created from tensor shares same memory of tensor and vice versa

In [13]:
numpy_arr = np.array([[1.0,2.0,3.0],
                     [10.0,20.0,30.0],
                     [100.0,200.0,300.0]])
numpy_arr

array([[  1.,   2.,   3.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [14]:
tensor_from_numpy = torch.from_numpy(numpy_arr)
tensor_from_numpy

tensor([[  1.,   2.,   3.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [15]:
tensor_from_numpy[0] = 1
tensor_from_numpy

tensor([[  1.,   1.,   1.],
        [ 10.,  20.,  30.],
        [100., 200., 300.]], dtype=torch.float64)

In [16]:
numpy_arr # same memory esseeeee's

array([[  1.,   1.,   1.],
       [ 10.,  20.,  30.],
       [100., 200., 300.]])

In [17]:
np_array_one = np.array([4,8])
np_array_one

array([4, 8])

In [19]:
tensor_from_array_one = torch.as_tensor(np_array_one) # avoids making copies of your data
tensor_from_array_one

tensor([4, 8])

In [20]:
np_array_one[1] = 5
np_array_one

array([4, 5])

In [21]:
np_array_two = np.array([2,2])
np_array_two

array([2, 2])

In [22]:
tensor_from_array_two = torch.tensor(np_array_two) # make copy of data
tensor_from_array_two

tensor([2, 2])

In [23]:
np_array_two[1] = 4
np_array_two

array([2, 4])

In [24]:
tensor_from_array_two

tensor([2, 2])