In [1]:
import torch

In [2]:
random_tensor = torch.Tensor([[3,4,19],[2,71,4],[52,4,6]])

In [3]:
random_tensor

tensor([[ 3.,  4., 19.],
        [ 2., 71.,  4.],
        [52.,  4.,  6.]])

In [4]:
sorted_tensor, sorted_indices = torch.sort(random_tensor)

In [5]:
sorted_tensor

tensor([[ 3.,  4., 19.],
        [ 2.,  4., 71.],
        [ 4.,  6., 52.]])

In [6]:
sorted_indices

tensor([[0, 1, 2],
        [0, 2, 1],
        [1, 2, 0]])

In [8]:
tensor_float = torch.FloatTensor([-1.1, -2.2, 3.3])
tensor_float

tensor([-1.1000, -2.2000,  3.3000])

In [9]:
# change elements to positive torch.abs(tensor_float)

In [10]:
rand1 = torch.abs(torch.randn(2,3))
rand2 = torch.abs(torch.randn(2,3))

In [11]:
rand1

tensor([[0.2614, 1.6559, 0.5726],
        [0.3729, 0.5814, 0.9605]])

In [12]:
rand2

tensor([[1.9377, 1.7197, 0.8714],
        [0.4051, 1.1099, 0.0790]])

In [15]:
add1 = rand1 + rand2 #elementwise addition
add1

tensor([[2.1991, 3.3757, 1.4440],
        [0.7779, 1.6912, 1.0394]])

In [16]:
add2 = torch.add(rand1, rand2) #also elementwise addition
add2

tensor([[2.1991, 3.3757, 1.4440],
        [0.7779, 1.6912, 1.0394]])

In [17]:
# torch.div(tensor1, tensor2) is elementwise division

In [18]:
tensor_mul = torch.mul(rand1, rand2)
tensor_mul

tensor([[0.5066, 2.8478, 0.4989],
        [0.1510, 0.6452, 0.0759]])

In [22]:
tensor_clamp = torch.clamp(rand1, min=0.3, max=1.5) # creates min and max threshold for all elements
tensor_clamp

tensor([[0.3000, 1.5000, 0.5726],
        [0.3729, 0.5814, 0.9605]])

In [23]:
t1 = torch.Tensor([1,2])
t2 = torch.Tensor([10,20])

In [24]:
dot_product = torch.dot(t1, t2)
dot_product

tensor(50.)

In [26]:
matrix = torch.Tensor([[1,2,3],
                      [4,5,6]])
vector = torch.Tensor([0,1,2])

In [28]:
matrix_vector = torch.mv(matrix,vector) # multiple matrix by vector (must be compatible) first v in matrix * v then repeat for second v in matrix
matrix_vector

tensor([ 8., 17.])

In [29]:
another_matrix = torch.Tensor([[10,20],
                              [10,0],
                              [0,5]])

In [30]:
matrix_mul = torch.mm(matrix, another_matrix) # matrix multiplication
matrix_mul

tensor([[ 30.,  35.],
        [ 90., 110.]])

In [34]:
torch.argmax(matrix_mul, dim=1) # argmin available

tensor([1, 1])