In [1]:
import torch
print(torch.get_default_dtype())

torch.float32


In [2]:
torch.set_default_dtype(torch.float64)
print(torch.get_default_dtype())

torch.float64


In [15]:
tensor_arr = torch.Tensor([[1,2,3],[4,5,6]])
tensor_arr

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [5]:
torch.is_tensor(tensor_arr)

True

In [6]:
torch.numel(tensor_arr)

6

In [8]:
tensor_uninitialised = torch.Tensor(2,2)

In [9]:
tensor_uninitialised

tensor([[ 0.0000e+00, -1.0842e-19],
        [ 4.9426e-04,  4.6577e-10]])

In [11]:
tensor_initialised = torch.rand(2,2)
tensor_initialised

tensor([[0.5324, 0.3170],
        [0.5813, 0.5630]])

In [19]:
tensor_int = torch.tensor([5,3]).type(torch.IntTensor)
tensor_int

tensor([5, 3], dtype=torch.int32)

In [21]:
tensor_fill = torch.full((2,6), fill_value=10)
tensor_fill

tensor([[10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10.]])

In [22]:
tensor_eye = torch.eye(6)
tensor_eye

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [25]:
non_zero = torch.nonzero(tensor_eye)
non_zero # shows you where non zero are

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3],
        [4, 4],
        [5, 5]])

In [10]:
i = torch.tensor([[0,1,1],[2,2,0]])
v = torch.tensor([3,4,5], dtype=torch.float32)
sparse_tensor = torch.sparse_coo_tensor(i,v,[2,5])
sparse_tensor.data

tensor(indices=tensor([[0, 1, 1],
                       [2, 2, 0]]),
       values=tensor([3., 4., 5.]),
       size=(2, 5), nnz=3, layout=torch.sparse_coo)

In [17]:
initial_tensor = torch.rand(2,3)
initial_tensor

tensor([[0.5711, 0.3022, 0.3385],
        [0.0787, 0.8583, 0.7382]])

In [20]:
initial_tensor.fill_(10)

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [21]:
initial_tensor.add(3)

tensor([[13., 13., 13.],
        [13., 13., 13.]])

In [15]:
initial_tensor.add_(3) # in place "add_" adds to original tensor

tensor([[13., 13., 13.],
        [13., 13., 13.]])

In [18]:
new_tensor = torch.rand(2,3)
new_tensor.fill_(15)

tensor([[15., 15., 15.],
        [15., 15., 15.]])

In [19]:
new_tensor.sqrt_()
new_tensor

tensor([[3.8730, 3.8730, 3.8730],
        [3.8730, 3.8730, 3.8730]])

In [20]:
x = torch.linspace(start=0.1, end=10.0, steps=15)
x

tensor([ 0.1000,  0.8071,  1.5143,  2.2214,  2.9286,  3.6357,  4.3429,  5.0500,
         5.7571,  6.4643,  7.1714,  7.8786,  8.5857,  9.2929, 10.0000])

In [21]:
tensor_chunk = torch.chunk(x,3,0)
tensor_chunk

(tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286]),
 tensor([3.6357, 4.3429, 5.0500, 5.7571, 6.4643]),
 tensor([ 7.1714,  7.8786,  8.5857,  9.2929, 10.0000]))

In [24]:
# can concatenate tensors using
torch.cat((tensor_chunk[0], tensor_chunk[1], torch.tensor([3.0,4.0,5.0])),0)

tensor([0.1000, 0.8071, 1.5143, 2.2214, 2.9286, 3.6357, 4.3429, 5.0500, 5.7571,
        6.4643, 3.0000, 4.0000, 5.0000])

In [3]:
random_tensor = torch.Tensor([[3,4,9],[2,7,4]])
random_tensor[0,1]

tensor(4.)

In [4]:
random_tensor[1:,1:]

tensor([[7., 4.]])

In [5]:
random_tensor.size()

torch.Size([2, 3])

In [9]:
random_tensor.view(6)

tensor([3., 4., 9., 2., 7., 4.])

In [10]:
random_tensor.shape

torch.Size([2, 3])

In [14]:
tensor_unsqueeze = torch.unsqueeze(random_tensor,2)
tensor_unsqueeze

tensor([[[3.],
         [4.],
         [9.]],

        [[2.],
         [7.],
         [4.]]])

In [15]:
tensor_unsqueeze.shape

torch.Size([2, 3, 1])

In [22]:
initial_tensor

tensor([[10., 10., 10.],
        [10., 10., 10.]])

In [24]:
tensor_transpose = torch.transpose(initial_tensor, 0, 1)
tensor_transpose

tensor([[10., 10.],
        [10., 10.],
        [10., 10.]])